In [21]:
import numpy as np

In [22]:
a = np.array([[1, 2, 3 ,4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]
             ])

print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
cal = a.sum(axis = 0) #sum vertically

# use axis = 1 -- sum horizontally

In [24]:
cal

array([15, 18, 21, 24])

In [39]:
percent = 100*a/cal.reshape(1, 4) 

"""
 Dimentions of a and cal matrices are not same, computation is possible because of the Broadcasting feature in numPy
"""

'\n Dimentions of a and cal matrices are not same, computation is possible because of the Broadcasting feature in numPy\n'

In [26]:
percent

array([[ 6.66666667, 11.11111111, 14.28571429, 16.66666667],
       [33.33333333, 33.33333333, 33.33333333, 33.33333333],
       [60.        , 55.55555556, 52.38095238, 50.        ]])

In [27]:
np.array([1, 2, 3, 4]) + 100

array([101, 102, 103, 104])

In [28]:
a + np.array([1, 2, 3, 4])

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [29]:
a = np.random.randn(5)

In [30]:
a

array([ 0.68076237, -0.90690519,  0.45132407, -0.46625972,  0.30587735])

In [31]:
a.shape # Rank 1 array 

# neither a row vector nor column vector

(5,)

In [32]:
a.T # Transpose of a

array([ 0.68076237, -0.90690519,  0.45132407, -0.46625972,  0.30587735])

In [33]:
a.T.shape

(5,)

In [34]:
np.dot(a, a.T)

1.800566911676029

In [35]:
a = np.random.randn(5, 1)

In [36]:
a

array([[-0.39345419],
       [-1.93216037],
       [ 0.31097178],
       [-0.68948634],
       [-1.38184025]])

In [37]:
a.T

array([[-0.39345419, -1.93216037,  0.31097178, -0.68948634, -1.38184025]])

In [38]:
assert(a.shape == (5, 1))

np.dot(a, a.T)

array([[ 0.1548062 ,  0.76021659, -0.12235315,  0.27128129,  0.54369084],
       [ 0.76021659,  3.73324369, -0.60084735,  1.33219818,  2.66993697],
       [-0.12235315, -0.60084735,  0.09670345, -0.21441079, -0.42971333],
       [ 0.27128129,  1.33219818, -0.21441079,  0.47539141,  0.95275998],
       [ 0.54369084,  2.66993697, -0.42971333,  0.95275998,  1.90948249]])